### ISSUE TITLE
[Task] Apply yarn format:apply to ./src/ 

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat-web#740]
Dependent on https://github.com/cryostatio/cryostat-web/pull/753
Dependent on https://github.com/cryostatio/cryostat-web/pull/747

There are around 500 fixes that can be applied automatically with the new eslint plugin `import/order`. 
Unfortunately it seems `import/first` has to be disabled because of problems with mocking the Date system time, which needs to be mocked before imports in the `DateTimePicker.test.tsx`.

Then `yarn eslint:apply` can be safely applied to every PR before pushing. 

There is additional task of fixing ALL eslint warnings manually so that the CI can start to check for it. That might be another chore if it sounds like a good idea.

I will prefer to open a PR when there are not as many open right now so that rebases aren't painful.

- [x] https://github.com/cryostatio/cryostat-web/pull/753
- [x]  https://github.com/cryostatio/cryostat-web/pull/747

## Tasks

- [ ] Apply yarn format:apply to automatically fix fixable eslint issues
- [ ] Manually go through all eslint warnings to fix them
- [ ] Re-enable `yarn eslint` within `ci.yaml` as part of the CI automation process

**Comment by andrewazores** [comment]
> Then yarn eslint:apply can be safely applied to every PR before pushing. There is additional task of fixing ALL eslint warnings manually so that the CI can start to check for it. That might be another chore if it sounds like a good idea.

https://github.com/cryostatio/cryostat-web/pull/208

I had the intent to do that quite a while ago, and obviously at that time I also just gave up on it. But, I think the codebase now is actually in overall better shape, and we have a lot more automated tooling that should help. So perhaps it's an easier task despite the fact that there is a lot more code now.

**Comment by maxcao13** [comment]
Oh, I see. That's why the `run: yarn lint` in the ci.yaml has been disabled. 

I do think it is not too hard for our codebase to be cleaned up for the closed task. Okay, I will add an additional subtask to this task to manually fix the warnings. Shouldn't be too painful I think. I will just start after those PRs are merged to save extra work.
