### ISSUE TITLE
[Story] Consistent unit test framework

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#848]
## Describe the feature

Right now, our unit framework needs refactoring to be more consistent the way we extract elements. With this, we can also move localization step into a single place. 

Some new test setups also need documenting. For example, test with different screen sizes, test with a specific locale, etc.

## Tasks

- [ ] #661 
- [ ] #665 
- [ ] #792 
- [ ] Extract common logic (i.e. look for buttons, texts, or dropdowns) into utility module, similar to `Common.tsx`.
- [ ] Document how to test console with different screen sizes.
- [ ] If possible, fix `can't update on unmounted component` warnings. Mostly relating `<Select />` component.

**Comment by tthvo** [comment]
This looks like it could help us with visual testing. Storybook is actually also included as a dev deps when creating project with PF seed.

https://storybook.js.org/tutorials/visual-testing-handbook/react/en/workflow/

**Comment by andrewazores** [comment]
> Storybook is actually also included as a dev deps when creating project with PF seed.

Indeed:

https://github.com/cryostatio/cryostat-web/pull/143

We can bring it back if we're actually going to start using it.

**Comment by tthvo** [comment]
https://github.com/cryostatio/cryostat-web/pull/914#issuecomment-1478380828

**Comment by tthvo** [comment]
https://github.com/patternfly/patternfly-next-react-demo-app#running-tests
